version: '3.0'
services:
  pagomunicipal_internal_sso_web_prod:
    container_name: pagomunicipal_internal_sso_web_prod
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_SECRET_NAME=PAGOMUNICIPAL-SECURITY-WEB
        - REACT_APP_API_SSO=http://3.89.197.239:9760
        - REACT_APP_API_BACKEND=http://3.89.197.239:9760
    image: pagomunicipal_internal_sso_web_prod
    restart: unless-stopped
    ports:
      - '9001:80'
      
