version: '3.0'
services:
  tse_external_sso_web_qa:
    container_name: tse_external_sso_web_qa
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_SECRET_NAME=TSE-SECURITY-WEB
        - REACT_APP_API_SSO=http://192.168.79.67:9761
        - REACT_APP_API_BACKEND=http://192.168.79.67:9761
    image: tse_external_sso_web_qa
    restart: unless-stopped
    ports:
      - '9001:80'
      
