drop table ROL_FORM_ACTION;
drop table form_action;
drop table form;
drop table action;
drop table method;
drop table form_group;
drop table users;
drop table company;
drop table rol;
drop table system;
drop table element;
drop table element_type;
drop table entiti;

drop sequence "TRAZ_CB_ADA"."ACTION_SEQUENCE";
drop sequence "TRAZ_CB_ADA"."ELEMENT_SEQUENCE";
drop sequence "TRAZ_CB_ADA"."ELEMENT_TYPE_SEQUENCE";
drop sequence "TRAZ_CB_ADA"."ENTITI_SEQUENCE";
drop sequence "TRAZ_CB_ADA"."FORM_ACTION_SEQUENCE";
drop sequence "TRAZ_CB_ADA"."FORM_GROUP_SEQUENCE";
drop sequence "TRAZ_CB_ADA"."FORM_SEQUENCE";
drop sequence "TRAZ_CB_ADA"."METHOD_SEQUENCE";
drop sequence "TRAZ_CB_ADA"."ROL_FORM_ACTION_SEQUENCE";
drop sequence "TRAZ_CB_ADA"."ROL_SEQUENCE";
drop sequence "TRAZ_CB_ADA"."COMPANY_SEQUENCE";
drop sequence "TRAZ_CB_ADA"."SYSTEM_SEQUENCE";
drop sequence "TRAZ_CB_ADA"."USERS_SEQUENCE";
drop sequence "TRAZ_CB_ADA"."HIBERNATE_SEQUENCE";


select * from rol_form_action;
select * from form_action;
select * from users;
select * from rol;
select * from form;
select * from form_Group;
select * from action;
select * from method;
select * from system;

delete from rol_form_action;
delete from form_action;
delete from users;
delete from rol;
delete from form;
delete from system;
delete from form_Group;
delete from action;
delete from method;
delete from system;
 
 
-- SYSTEM
insert into system (id,name,created_by,updated_by, created_at, updated_at) values (system_sequence.nextval,'TECUN_WEB',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null);
insert into system (id,name,created_by,updated_by, created_at, updated_at) values (system_sequence.nextval,'IXMUKANE_APP',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null);
insert into system (id,name,created_by,updated_by, created_at, updated_at) values (system_sequence.nextval,'IXMUKANE_WEB',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null);

-- ROL
insert into rol (id,name,created_by,updated_by, created_at, updated_at) values (rol_sequence.nextval,'admin',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null);

-- METHOD
insert into method (id,name,created_by,updated_by, created_at, updated_at) values (method_sequence.nextval,'GET',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null);
insert into method (id,name,created_by,updated_by, created_at, updated_at) values (method_sequence.nextval,'POST',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null);
insert into method (id,name,created_by,updated_by, created_at, updated_at) values (method_sequence.nextval,'PUT',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null);
insert into method (id,name,created_by,updated_by, created_at, updated_at) values (method_sequence.nextval,'DEL',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null);
insert into method (id,name,created_by,updated_by, created_at, updated_at) values (method_sequence.nextval,'PATH',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null);
insert into method (id,name,created_by,updated_by, created_at, updated_at) values (method_sequence.nextval,'OPTION',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null);

-- FORM GROUP 
-- TECUN WEB
insert into form_Group (id,name,item_order,show_in_menu,is_group_of_pages,icon,created_by,updated_by, created_at, updated_at, system_id)  values (form_Group_sequence.nextval,'Principal',1,1,0,'home',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,1);
insert into form_Group (id,name,item_order,show_in_menu,is_group_of_pages,icon,created_by,updated_by, created_at, updated_at, system_id)  values (form_Group_sequence.nextval,'Seguridad',2,1,1,'security',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,1);
insert into form_Group (id,name,item_order,show_in_menu,is_group_of_pages,icon,created_by,updated_by, created_at, updated_at, system_id)  values (form_Group_sequence.nextval,'Barriles',2,1,1,'security',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,1);
insert into form_Group (id,name,item_order,show_in_menu,is_group_of_pages,icon,created_by,updated_by, created_at, updated_at, system_id)  values (form_Group_sequence.nextval,'Tarimas',2,1,1,'security',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,1);
insert into form_Group (id,name,item_order,show_in_menu,is_group_of_pages,icon,created_by,updated_by, created_at, updated_at, system_id)  values (form_Group_sequence.nextval,'Pitas/Tanques',2,1,1,'security',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,1);
-- IXMUKANE MOVIL
insert into form_Group (id,name,item_order,show_in_menu,is_group_of_pages,icon,created_by,updated_by, created_at, updated_at, system_id)  values (form_Group_sequence.nextval,'Principal',1,1,0,'home',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,2);
insert into form_Group (id,name,item_order,show_in_menu,is_group_of_pages,icon,created_by,updated_by, created_at, updated_at, system_id)  values (form_Group_sequence.nextval,'Seguridad',10,1,1,'security',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,2);
insert into form_Group (id,name,item_order,show_in_menu,is_group_of_pages,icon,created_by,updated_by, created_at, updated_at, system_id)  values (form_Group_sequence.nextval,'Barriles',2,1,1,'battery-full',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,2);
insert into form_Group (id,name,item_order,show_in_menu,is_group_of_pages,icon,created_by,updated_by, created_at, updated_at, system_id)  values (form_Group_sequence.nextval,'Tarimas',3,1,1,'security',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,2);
insert into form_Group (id,name,item_order,show_in_menu,is_group_of_pages,icon,created_by,updated_by, created_at, updated_at, system_id)  values (form_Group_sequence.nextval,'Pitas/Tanques',4,1,1,'security',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,2);
-- IXMUKANE WEB
insert into form_Group (id,name,item_order,show_in_menu,is_group_of_pages,icon,created_by,updated_by, created_at, updated_at, system_id)  values (form_Group_sequence.nextval,'Principal',1,1,0,'home',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,3);
insert into form_Group (id,name,item_order,show_in_menu,is_group_of_pages,icon,created_by,updated_by, created_at, updated_at, system_id)  values (form_Group_sequence.nextval,'Seguridad',10,1,1,'security',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,3);
insert into form_Group (id,name,item_order,show_in_menu,is_group_of_pages,icon,created_by,updated_by, created_at, updated_at, system_id)  values (form_Group_sequence.nextval,'Datos maestros',2,1,1,'group_work',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,3);
insert into form_Group (id,name,item_order,show_in_menu,is_group_of_pages,icon,created_by,updated_by, created_at, updated_at, system_id)  values (form_Group_sequence.nextval,'Barriles',2,1,1,'battery-full',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,3);
insert into form_Group (id,name,item_order,show_in_menu,is_group_of_pages,icon,created_by,updated_by, created_at, updated_at, system_id)  values (form_Group_sequence.nextval,'Tarimas',3,1,1,'security',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,3);
insert into form_Group (id,name,item_order,show_in_menu,is_group_of_pages,icon,created_by,updated_by, created_at, updated_at, system_id)  values (form_Group_sequence.nextval,'Pitas/Tanques',4,1,1,'security',0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,3);

-- FORM  
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Inicio',1,'/',1,'home',1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Mi perfil',2,'/profile',1,'person',1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Usuarios',2,'/user',1,'people',1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Roles',2,'/rol',1,'supervised_user_circle',1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Acciones de rol',2,'/rolFormAction',0,'supervised_user_circle',1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Acciones',2,'/action',1,'call_to_action',1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Metodos',2,'/method',1,'supervised_user_circle',1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Acciones por formulario',2,'/formAction',1,'call_split',1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Grupo de formularios',2,'/formGroup',1,'insert_drive_file',1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Formularios',2,'/form',1,'chrome_reader_mode',1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Sistemas',2,'/system',1,'desktop_windows',1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Empresas',2,'/company',1,'apartment',1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Inicio',6,'/',1,'home',2,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'Home');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Mi perfil',7,'/profile',1,'person',2,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'Profile');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Barriles',8,'/barril',1,'battery-full',2,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'Barrel');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Tarimas',9,'/tarima',1,'dns',2,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'Pallet');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Inicio',11,'/',1,'home',3,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Mi perfil',12,'/profile',1,'person',3,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Paises',13,'/country',1,'view_list',3,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Ciudaddes',13,'/city',1,'view_list',3,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Tipo de barriles',13,'/barrelType',1,'view_list',3,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Tipas o tanques',13,'/pipe',1,'view_list',3,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Tipos de tarimas',13,'/pallet',1,'view_list',3,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Tipos De incidencias',13,'/incidentType',1,'view_list',3,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Tipos de maridajes',13,'/pairingType',1,'view_list',3,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Motivos de incidencias',13,'/incidenceReason',1,'view_list',3,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Proveedores',13,'/supplier',1,'view_list',3,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Productos',13,'/product',1,'view_list',3,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Bodegas',13,'/warehouse',1,'view_list',3,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Piezas',13,'/piece',1,'view_list',3,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Correlativos de procesos',13,'/process',1,'view_list',3,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Tipos de reparaciones',13,'/fixType',1,'view_list',3,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Motivos de baja',13,'/cancellationReason',1,'view_list',3,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');
INSERT INTO form (id,name,form_group_id,path,show_in_menu,icon,system_id,created_at,updated_at,created_by,updated_by,mobile_screen) values(form_sequence.nextval,'Motivo de traslado',13,'/transferReason',1,'view_list',3,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null,0,0,'');



-- ACTION
insert into action (id,name,path,method_id,created_by,updated_by, created_at, updated_at) values (action_sequence.nextval,'Crear','create',2,0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null);
insert into action (id,name,path,method_id,created_by,updated_by, created_at, updated_at) values (action_sequence.nextval,'Modificar','update',3,0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null);
insert into action (id,name,path,method_id,created_by,updated_by, created_at, updated_at) values (action_sequence.nextval,'Anular','cancel',5,0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null);
insert into action (id,name,path,method_id,created_by,updated_by, created_at, updated_at) values (action_sequence.nextval,'Listado','list',1,0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null);
insert into action (id,name,path,method_id,created_by,updated_by, created_at, updated_at) values (action_sequence.nextval,'Ver','view',1,0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null);
insert into action (id,name,path,method_id,created_by,updated_by, created_at, updated_at) values (action_sequence.nextval,'Eliminar','delete',4,0,0,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),null);

-- FORM_ACTION 
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,1,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,1,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,1,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,1,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,1,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,1,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,2,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,2,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,2,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,2,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,2,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,2,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,3,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,3,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,3,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,3,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,3,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,3,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,4,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,4,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,4,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,4,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,4,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,4,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,5,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,5,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,5,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,5,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,5,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,5,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,6,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,6,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,6,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,6,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,6,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,6,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,7,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,7,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,7,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,7,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,7,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,7,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,8,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,8,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,8,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,8,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,8,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,8,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,9,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,9,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,9,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,9,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,9,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,9,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,10,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,10,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,10,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,10,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,10,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,10,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,11,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,11,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,11,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,11,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,11,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,11,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,12,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,12,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,12,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,12,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,12,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,12,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,12,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,12,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,12,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,12,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,12,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,12,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,13,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,13,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,13,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,13,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,13,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,13,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,14,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,14,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,14,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,14,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,14,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,14,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,15,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,15,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,15,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,15,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,15,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,15,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,16,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,16,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,16,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,16,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,16,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,16,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,17,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,17,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,17,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,17,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,17,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,17,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,18,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,18,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,18,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,18,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,18,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,18,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,19,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,19,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,19,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,19,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,19,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,19,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,20,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,20,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,20,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,20,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,20,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,20,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,21,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,21,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,21,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,21,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,21,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,21,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,22,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,22,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,22,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,22,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,22,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,22,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,23,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,23,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,23,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,23,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,23,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,23,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,24,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,24,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,24,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,24,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,24,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,24,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,25,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,25,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,25,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,25,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,25,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,25,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,26,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,26,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,26,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,26,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,26,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,26,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,27,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,27,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,27,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,27,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,27,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,27,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,28,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,28,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,28,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,28,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,28,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,28,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,29,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,29,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,29,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,29,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,29,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,29,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,30,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,30,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,30,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,30,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,30,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,30,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,31,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,31,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,31,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,31,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,31,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,31,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,32,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,32,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,32,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,32,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,32,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,32,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);
insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,33,1,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,33,2,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,33,3,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,33,4,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,33,5,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);insert into form_action (id,form_id,action_id,item_order,created_by,updated_by, created_at, updated_at, is_the_rol) values (form_action_sequence.nextval,33,6,1,NULL,NULL,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),NULL,0);


-- ROL_FORM_ACTION
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,1,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,2,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,3,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,4,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,5,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,6,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,7,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,8,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,9,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,10,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,11,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,12,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,13,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,14,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,15,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,16,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,17,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,18,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,19,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,20,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,21,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,22,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,23,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,24,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,25,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,26,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,27,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,28,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,29,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,30,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,31,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,32,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,33,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,34,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,35,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,36,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,37,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,38,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,39,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,40,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,41,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,42,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,43,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,44,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,45,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,46,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,47,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,48,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,49,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,50,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,51,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,52,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,53,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,54,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,55,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,56,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,57,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,58,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,59,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,60,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,61,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,62,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,63,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,64,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,65,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,66,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,67,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,68,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,69,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,70,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,71,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,72,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,67,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,68,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,69,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,70,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,71,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,72,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,73,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,74,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,75,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,76,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,77,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,78,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,79,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,80,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,81,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,82,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,83,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,84,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,85,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,86,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,87,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,88,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,89,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,90,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,91,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,92,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,93,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,94,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,95,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,96,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,97,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,98,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,99,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,100,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,101,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,102,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,103,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,104,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,105,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,106,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,107,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,108,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,109,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,110,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,111,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,112,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,113,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,114,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,115,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,116,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,117,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,118,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,119,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,120,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,121,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,122,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,123,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,124,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,125,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,126,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,127,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,128,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,129,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,130,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,131,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,132,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,133,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,134,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,135,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,136,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,137,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,138,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,139,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,140,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,141,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,142,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,143,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,144,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,145,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,146,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,147,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,148,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,149,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,150,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,151,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,152,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,153,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,154,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,155,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,156,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,157,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,158,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,159,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,160,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,161,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,162,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,163,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,164,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,165,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,166,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,167,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,168,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,169,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,170,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,171,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,172,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,173,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,174,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,175,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,176,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,177,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,178,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,179,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,180,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,181,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,182,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,183,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,184,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,185,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,186,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,187,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,188,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,189,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,190,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,191,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,192,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );
INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,193,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,194,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,195,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,196,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,197,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );INSERT INTO ROL_FORM_ACTION (id,form_action_id,rol_id, created_at) values (ROL_FORM_ACTION_SEQUENCE.nextval,198,1,TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss') );

-- SELECT * FROM COMPANY
insert into company (id,name, created_by, updated_by,created_at)  values(COMPANY_SEQUENCE.nextval,'Añejos de Altura',0,0, TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'));
insert into company (id,name, created_by, updated_by,created_at)  values(COMPANY_SEQUENCE.nextval,'Casa Botran',0,0, TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'));

-- USERS 
insert into users (id,email,email_verified, image_url,name,password,provider,provider_id,rol_id, created_by, updated_by,created_at,is_cancel,company_id) 
values(1,'netneill@hotmail.com',0,null,'jorge','$2a$10$EJJ2s.XTKxWkwDaprqJdTuglXEhUdBOOARDKexBNQdX8lHfyOB5M.','local',null,1,0,0, TO_CHAR(SYSDATE,'DD/MM/YYYY hh:mm:ss'),0,1);

-- clave de jorge es jorge1919 DELETE FROM form where id=16
select * from form_group;
select * from form;
select * from system;
select * from action;
select * from rol_form_action;
select * from users;
select * from form_action ;
select * from method order by id;
select * from rol;

-- ROL FORM ACTION
select	fa.id, fa.form_id, fa.action_id, fa.item_order, 
					case when (select count(*) from rol_form_action rfa where rfa.form_action_id=fa.id and rfa.rol_id= 1 )>0 then 1 else 0 end is_the_rol, 
					f.name form, fg.name formGroup, a.name action, fa.id form_action_id, 1 rol_id, f.path formPath, a.path actionPath,s.name 
			from form_action fa 
			inner join form f on fa.form_id=f.id
			inner join system s on f.system_id=s.id
			inner join form_group fg on f.form_group_id=fg.id 
			inner join action a on fa.action_id=a.id


-- GET MENU
select distinct f.*, fg.item_order
			from form f 
      inner join form_group fg on f.form_group_id=fg.id
			inner join system s on f.system_id=s.id 
			inner join form_action fa on f.id= fa.form_id 
			inner join action a on a.id=fa.action_id 
			inner join rol_form_action rfa on fa.id=rfa.form_action_id 
			where  rfa.rol_id = 1 and s.name= 'TRAZA_APP'
      ORDER BY fg.item_order ASC
      
select distinct f.*, fg.item_order 
inner join form_group fg on f.form_group_id=fg.id from form f inner join system s on f.system_id=s.id inner join form_action fa on f.id= fa.form_id inner join action a on a.id=fa.action_id inner join rol_form_action rfa on fa.id=rfa.form_action_id 
where  rfa.rol_id = 1 and s.name= 'TRAZA_APP'
ORDER BY fg.item_order ASC 
/*VALIDACIONES*/
delete from element;
delete from element_type;
delete from entiti;

DBCC CHECKIDENT ('entiti', RESEED, 0)
DBCC CHECKIDENT ('element_type', RESEED, 0)
DBCC CHECKIDENT ('element', RESEED, 0)

insert into entiti (name,version) values('users',1) ;
insert into element_type (name,version)up values ('input',1), ('hidden',1), ('h3',1), ('password',1), ('checkbox',1), ('dropdown',1), ('textarea',1), ('file',1);

insert into element (created_at,idelement,is_create,is_delete,is_required,is_unique, is_update,
		label,mask,mask_property,order_element,pattern, pattern_message,
updated_at, version, element_type_id, entiti_id) 
values
(getdate(),'email',1,0,1,1,1,
'Correo electronico','','',1,'^([\w-\\.]+){1,25}@([\w]+){2,25}.[a-z]{2,10}$','Campo requiere un correo válido (Ejemplo: jorge@gmail.com)',
null,1,1,1),
(getdate(),'name',1,0,1,1,1,
'Usuario','','',1,'^([\w-\\.]+){4,20}$','Campo requiere un texto de 4 a 20 caracteres (Ejemplo: jorgesantos1)',
null,1,1,1)

select * from element
select * from entiti
select * from element_type



